### ISSUE TITLE
Where do I place the custom mappings?

### ISSUE THREAD

**Issue by pcrutchfield** [mwilliamson/mammoth-wordpress-plugin#1]
Hello Michael, 

Thanks for responding to my email. I am using the WordPress plugin to import license docs to a WordPress site. Because stying is critical to these items I need to use some custom mapping. I get the following error using default settings:
[Heading EULA.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/554386/Heading.EULA.docx)

Warning: Unrecognised paragraph style: 'Heading EULA' (Style ID: HeadingEULA)
Warning: Unrecognised paragraph style: 'Heading Software Title' (Style ID: HeadingSoftwareTitle)
Warning: Unrecognised run style: 'Preamble' (Style ID: Preamble)
Warning: Unrecognised paragraph style: 'Compliance Border Above' (Style ID: ComplianceBorderAbove)
Warning: Unrecognised paragraph style: 'List Style 4' (Style ID: ListStyle4)
Warning: Unrecognised paragraph style: 'List Style 5' (Style ID: ListStyle5)
Warning: Unrecognised paragraph style: 'List Style 2' (Style ID: ListStyle2)
Warning: Unrecognised paragraph style: 'List Style 3' (Style ID: ListStyle3)

I would like to add the following custom mappings to the plugin so anyone using the converter gets the correct styles (with help from CSS). 

p[style-name='Heading EULA'] => h1.headingeula:fresh
p[style-name='Heading Software Title'] => h1.headingsoftwaretitle:fresh
p[style-name='Preamble'] => 
p[style-name='Compliance Border Above'] => 
p[style-name='List Style 4'] => ul.liststyle4 > li
p[style-name='List Style 5'] => ul.liststyle5  > li
p[style-name='List Style 2’] => ol.liststyle2  > li
p[style-name='List Style 3’] => ol.liststyle3  > li

I must be missing something but I see how to style the mappings but not where to place them in the plugin.
- Pierre

**Comment by mwilliamson** [comment]
When using the WordPress plugin, the only way to add your own custom style map is to use embedded style maps. Their usage is described on the [plugin page](https://wordpress.org/plugins/mammoth-docx-converter/), under the heading "Embedded style maps" near the bottom. Would that work for your use case?

**Comment by pcrutchfield** [comment]
Possibly. Does it work in Safari? Tried to use it but not seeing a result message or any indication that it worked. 

Will users have to use the tool every time they upload a new doc? We 100s of these to do with each product release. 

- Pierre

**Comment by mwilliamson** [comment]
Does which bit work in Safari? Embedding a style map, or importing a document with an embedded style map? If the former, then hitting "Embed" (after you've uploaded the original document and entered your style map) should download the new version of the document. I don't have access to a Mac, so can't test on Safari.

The embedded style map should be retained across saves, so you can use a single document as a template.

**Comment by pcrutchfield** [comment]
No problem. Used Chrome and got to see how it works. Most of the folks using this will be on Windows so no need to figure out the Safari issues.

- Pierre

**Comment by mwilliamson** [comment]
Glad to hear you got it working. Does this resolve the issue for you?

**Comment by mwilliamson** [comment]
Closing since it sounds like it's all sorted.
