### ISSUE TITLE
Style applied / interpreted on each character instead of word

### ISSUE THREAD

**Issue by Jugibur** [mwilliamson/mammoth-wordpress-plugin#11]
Hello,
I have the strange phenomenon that every now and then, for a word, the styling is interpreted internally per letter. 
Even if I reset the styling to "default / standard" and reformat the word, this error remains.
Only when I completely rewrite the word and reassign the style, it then works again.
Of course, you can't be held responsible for the bugs in Word, so just a suggestion on how to solve this problem anyway.
So my idea is:
If letters with identical, consecutive styles appear, interpret these letters as one word with only one style.

Would this perhaps be possible and could it work or is there another work-around? Thanks a lot!

**Comment by mwilliamson** [comment]
Could you upload a minimal example document?

**Comment by mwilliamson** [comment]
The issue is with the style map you've used: I think you'll want to use non-fresh elements for the parent elements that you don't want opened and closed, for instance:

```
r[style-name='preis'] => div.menu-price-wrapper > span.menu-price
```

**Comment by Jugibur** [comment]
Yes, this is a good work around. I don't remember why I built it this way, but it was quite complex CSS formatting. It still works now though, as I've seen. Thanks for your help!

**Comment by mwilliamson** [comment]
No worries!
