### ISSUE TITLE
Problems with default image filename (long import time)

### ISSUE THREAD

**Issue by marcinswirek** [mwilliamson/mammoth-wordpress-plugin#12]
Hi
As I've faced a lot of problems with image upload time, which is getting longer and longer together with the number of images in Media Library, I made an investigation. As I have found out, based on plugin code Wordpress is creating file `word-image.png`. But that is only for the first time. The second image filename is `word-image-1.png`. Problem appears when we have a lot of images called `word-image-{$incremented_number}`, because plugin by default wants to create image `word-image.png`, but let's say, that this name already exists in Library, so wordpress is incrementing filename, and check if `word-image-1.png` exists, if no, then ok. If yes, WP check next one, and the next one. In case we have images called from `word-image.png` to `word-image-1000.png`, a thousand of ajax request is being carried out to find the first free filename with above pattern. My solution for this problem is very simple. I wrote simple function to generate 9 digit filename, and the problem has gone.

**Comment by mwilliamson** [comment]
Ah, I didn't realise that's how WordPress finds unique filenames -- that seems less than ideal!

Perhaps a timestamp might be nicer to include in the filename, rather than an arbitrary string?

**Comment by marcinswirek** [comment]
Sure. Timestamp should also works fine. It will be unique for sure.

**Comment by mwilliamson** [comment]
This should be addressed in the latest version of the plugin, if you want to give it a go?

**Comment by marcinswirek** [comment]
Sure. i think it worth a try. Should I prepare a PR?

**Comment by mwilliamson** [comment]
Sorry, I meant that I've already released a new version that hopefully fixes the issue.
