### ISSUE TITLE
Problem with custom style map change heading line 1 to h2

### ISSUE THREAD

**Issue by zhipeng001** [mwilliamson/mammoth-wordpress-plugin#13]
Hi there!
First, amazing work. I have installed the plugin on my website. But I encountered a problem when using options-plugin.
I want change heading1 to h2 by using custom style map. But it didn't work.
my mammoth-options.js is below

`function MAMMOTH_OPTIONS(mammoth) {
    var styleMap = [
        "p[style-name^='Heading'] => h2:fresh",
	"p[style-name='Heading 1'] => h2:fresh",
        "p[style-name^='1'] => h2",
        "p[style-name='标题1'] => h2:fresh",
        "p[style-name='标题2'] => h3:fresh",
 ];
    console.log('styleMap load!-7');
}`

And the docx file is attached.
[demo-en.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/8831961/demo-en.docx)

Can you figure out what problem is?

**Comment by mwilliamson** [comment]
I might have misread, but it looks like to me like you're not actually returning anything from the function. You'll need to return an options object from `MAMMOTH_OPTIONS`.

On Fri, 3 Jun 2022, at 12:34 PM, zhipeng001 wrote:
> 
> 
> 
> Hi there!
> First, amazing work. I have installed the plugin on my website. But I encountered a problem when using options-plugin.
> I want change heading1 to h2 by using custom style map. But it didn't work.
> my mammoth-options.js is below
> `function MAMMOTH_OPTIONS(mammoth) {
> var styleMap = [
> "p[style-name^='Heading'] => h2:fresh",
> "p[style-name='Heading 1'] => h2:fresh",
> "p[style-name^='1'] => h2",
> "p[style-name='标题1'] => h2:fresh",
> "p[style-name='标题2'] => h3:fresh",
> 
> `];
> console.log('styleMap load!-7');
`

**Comment by zhipeng001** [comment]
Fixed, thank you very much.
