### ISSUE TITLE
Custom post types support

### ISSUE THREAD

**Issue by foldesistudio** [mwilliamson/mammoth-wordpress-plugin#17]
Hi there,

I hope this email finds you well. In regards to your question, I wanted to confirm whether or not the plugin we offer supports custom post types with your awesome plugin. 

If you could kindly provide me with more details, I would be happy to look into this for you and get back to you as soon as possible.

Thank you for your time and I look forward to hearing from you soon.

Best regards,

[Mihály](https://foldesistudio.hu)

**Comment by mwilliamson** [comment]
I think there's been some kind of mistake: I'm afraid I haven't asked any questions about your plugin.

**Comment by foldesistudio** [comment]
I mean... Does your plugin offer support for custom post type support?
