### ISSUE TITLE
Cannot update to v1.4

### ISSUE THREAD

**Issue by gbc46** [mwilliamson/mammoth-wordpress-plugin#2]
I just tried to do the standard wordpress update for this great plugin but it failed due to "probable incompatible permissions" - this didn't happen with the previous version or with other plugins that I updated at the same time - unfortunately I don't seem to be able to get any further information on exactly which permissions may have been wrong and as far as I know they are all standard. Any idea why this update may have caused this to happen?

**Comment by mwilliamson** [comment]
On Wed, 21 Dec 2016 01:46:06 -0800
gbc46 <notifications@github.com> wrote:

> I just tried to do the standard wordpress update for this great
> plugin but it failed due to "probable incompatible permissions" -
> this didn't happen with the previous version or with other plugins
> that I updated at the same time - unfortunately I don't seem to be
> able to get any further information on exactly which permissions may
> have been wrong and as far as I know they are all standard. Any idea
> why this update may have caused this to happen?
> 

Is that the exact phrase that WordPress displays?

I'm not sure why this particular update would fail: it only updates
existing files, much the same as previous updates. Perhaps try
uninstalling and reinstalling the plugin?

**Comment by gbc46** [comment]
The exact phrase copied from Wordpress is "Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions." As I said I haven't altered any of the standard permissions - not sure I would know how to - maybe I need to ask my host site? Is there any way I can get a more detailed or specific message?

**Comment by mwilliamson** [comment]
On Wed, 21 Dec 2016 03:05:29 -0800
gbc46 <notifications@github.com> wrote:

> The exact phrase copied from Wordpress is "Update Failed: The update
> cannot be installed because we will be unable to copy some files.
> This is usually due to inconsistent file permissions." As I said I
> haven't altered any of the standard permissions - not sure I would
> know how to - maybe I need to ask my host site? Is there any way I
> can get a more detailed or specific message?
> 


Asking your host sounds like the best idea. All of the files installed
by Mammoth need to be writable by the web server for updating through
the WordPress UI to work. So far as I know, Mammoth doesn't do anything
unusual, so I wouldn't have thought that this would be a problem
specific to Mammoth, but happy to be corrected if it turns out
otherwise.

Did you try deactivating, uninstalling and reinstalling the plugin?

**Comment by mwilliamson** [comment]
Did you manage to get this sorted?

**Comment by gbc46** [comment]
My sincere apologies for not getting back to you - I had intended to and then Christmas took over from everything. Yes, I asked my ISP and he reset all the permissions and then the update worked perfectly - he did say that perhaps the permissions had been wrong since the system from moved from another ISP but I think that would be strange since other plugins had updated fine, however I have no idea why just some of the permissions might get changed. Anyway the main thing is that the Mammoth plugin updated fine once the permissions were reset and its now working just as well as it always did - many thanks for your help. Its a great plugin. All the best for 2017.

**Comment by mwilliamson** [comment]
No problem at all, glad to hear you got it sorted.
