### ISSUE TITLE
12*12 pixel pictures can`t insert

### ISSUE THREAD

**Issue by qslwp** [mwilliamson/mammoth-wordpress-plugin#20]
I have several 12*12 pixel pictures in a docx file. I cannot successfully insert chapters using this plug-in.

**Comment by qslwp** [comment]
> I have several 12*12 pixel pictures in a docx file. I cannot successfully insert chapters using this plug-in.

![VG$)RX(ZK(64@7DUWHGZ$2](https://github.com/mwilliamson/mammoth-wordpress-plugin/assets/39366093/9066b5af-047c-4b68-9a07-831ff0e7ca33)
The pixels of these pictures are very low

**Comment by mwilliamson** [comment]
Could you provide a minimal example document? Do any documents with images work? Do you get any messages?

**Comment by qslwp** [comment]
I didn't get any error messages. 
You can try this file
[test.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/15142261/test.docx)

**Comment by qslwp** [comment]
Sorry, I get these messages.

Warning: Image of type image/x-wmf is unlikely to display in web browsers
Warning: An unrecognised element was ignored: {urn:schemas-microsoft-com:office:office}OLEObject

**Comment by mwilliamson** [comment]
The issue is that the images are WMF images, and Mammoth doesn't support converting them into other image formats such as PNGs or JPEGs. If you want them to be converted, you'll need to convert them in the source document to a format that's supported by browsers.
