### ISSUE TITLE
Please delete this file

### ISSUE THREAD

**Issue by bisherbas** [mwilliamson/mammoth-wordpress-plugin#5]
https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1692060

I uploaded the correct file in the issue thread. I uploaded this one by mistake. Please delete it. Thank you.

**Comment by mwilliamson** [comment]
I'm afraid I don't know of any way that I can delete a file that you've uploaded. I'd suggest getting in touch with GitHub themselves.

**Comment by bisherbas** [comment]
Thanks!
