### ISSUE TITLE
Underlined words are converted without the underlines

### ISSUE THREAD

**Issue by bisherbas** [mwilliamson/mammoth-wordpress-plugin#6]
[Underline.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1693108/Underline.docx)

[Underline_html.txt](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1693109/Underline_html.txt)

**Comment by mwilliamson** [comment]
This is by design, since underscores in web pages are normally used to indicate hyperlinks. If you'd like to map underscores to something, you'll have to use a custom style map.

**Comment by bisherbas** [comment]
Got it. Can you tell me how to configure a "custom style map"? Honestly, I don't even know what it is.

**Comment by mwilliamson** [comment]
You can find details on the [plugin page](https://wordpress.org/plugins/mammoth-docx-converter/) under the heading "Embedded style maps".

**Comment by bisherbas** [comment]
Thank you so much!
