### ISSUE TITLE
Empty links being pulled through by importer

### ISSUE THREAD

**Issue by DaveConvery** [mwilliamson/mammoth-wordpress-plugin#8]
Not a bug so much as the importer working perfectly and Word being odd, but we're seeing some empty links (no href element) being pulled through. In the Word doc they take the form <a name="_hlk[numeric_string]">, and when they're imported the name element is converted to an ID element with the post number added to the value as a prefix.

Would it be feasible to add an option to not import links that don't have an href value? We've struggled to identify why these links are being placed in Word in the first place, and it doesn't seem to be straightforward to delete them from a document once they're there.

**Comment by mwilliamson** [comment]
That sounds like the sort of HTML generated when the importer converts a bookmark. Do they appear in the list of bookmarks for the document, and if so, is it practical to delete them?

Alternatively, if you don't want to ignore all bookmarks, then you could write a document transform to get rid of them.

**Comment by DaveConvery** [comment]
That was it - they were hidden bookmarks. Forcing them to appear in the bookmarks menu has made them much more murderable. Thank you!
