### ISSUE TITLE
Links are splitted if special charaters

### ISSUE THREAD

**Issue by lupa18** [mwilliamson/mammoth-wordpress-plugin#9]
Hello, 

When .doc file has special character in link, ie: [comunicación](https://es.wikipedia.org/wiki/Comunicación), then the parser split it in several parts. The link seems to be well and actually works, but code is quite obfuscated. 

In this example result code will be similar to this: 
`
<a href="https://es.wikipedia.org/wiki/Comunicación">comunicaci</a><a href="https://es.wikipedia.org/wiki/Comunicación">ó</a><a href="https://es.wikipedia.org/wiki/Comunicación">n</a>
`

Is not crucial but I think is important that code is as clean as possible. 

thanks in advance

**Comment by mwilliamson** [comment]
Could you provide a minimal example document?

**Comment by lupa18** [comment]
Hello @mwilliamson and thanks!

yes, any .doc with Spanish tilde

example: [documento.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/3799331/documento.docx)

- the 1st paragraph is an example
- 3 last links also

**Comment by mwilliamson** [comment]
I've just released 1.15.0 which hopefully fixes the issue. Could you give it a go?

**Comment by lupa18** [comment]
Perfect ! fiexed ! thanks !!
